### PR TITLE
fix typo in f2py command

### PR DESCRIPTION
**Pull request by sunt05**
the second `-c` in the `f2py` command needs fixing

### CODE REVIEW

**Comment by Nicholaswogan** [comment]
Is this ready to merge?

**Comment by sunt05** [comment]
Sorry I was meant to only fix the typo in your README but apparently mixed in some changes for my local work. 
Will close this and do another PR properly.

**Comment by Nicholaswogan** [comment]
Also, by the way. My preferred method right now for doing complicated python wrappers to fortran is Cython: https://github.com/Nicholaswogan/fortran-cython-examples

**Comment by sunt05** [comment]
Thanks @Nicholaswogan for suggesting your other repo - I've noticed that and will have a more proper look shortly.

**Pull request closed without merging**
